services:
  web:
    build: .
    command: gunicorn issue_tracker.wsgi:application --config gunicorn.conf.py
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
  mysql_data: